[package]
name = "weatherapp"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0"
serde = { version = "1.0.200", features = ["derive"] }
reqwest = { version = "0.12.3", features = ["blocking", "json"] }
serde_json = "1.0"
